### ISSUE TITLE
split the cmdliner part from the core library

### ISSUE THREAD

**Issue by c-cube** [dbuenzli/uuidm#9]
separate opam files, rather than depopts, avoids unecessary recompilations and make dependencies more explicit.

**Comment by dbuenzli** [comment]
I'm not interested in micromanaging the `cmdliner` dependency. A lot of my libraries come with a cli helper tool that exercises the library functionality and is useful in its own way, but formally the library doesn't need it.

So you get the following choice: 

1. Things are kept as is. Maybe `opam` can try to improve the `dep-opts` supports so that packages with a dep-opt can be specified as dependency, I think it was supposed to be done at some point. I don't know what happened with it.
2. The `dep-opt` is dropped and all these packages are made to formally depend on `cmdliner` even though the library doesn't it.

What I'm *not* going to do is to have a `$(PKG)-cmdliner` package for all these libraries.

**Comment by c-cube** [comment]
alright.
